[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["interzoid_weather_update_to_slack_message"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/ScheduledTask","Category/Integration"]
  name = "interzoid_weather_update_to_slack_message"
  org = "internalslaimpl"
  version = "3.1.0"

